## Tarea Semana 7

---

*   Camilo Martínez Estay.
*   16 de octubre, 2024.


---

Escribir en formato CSR la matriz $A$ de tamaño $ 8 \times 8 $, con las siguientes entradas no cero:

\begin{align*}
A(1, 1) &= 3 \\
A(2, 1) &= 4 \\
A(6, 6) &= 5 \\
A(7, 1) &= 5 \\
A(7, 3) &= 8 \\
\end{align*}

Es decir, se pide encontrar el vector de valores, punteros de las filas, e índices de columnas.



En el documento de la semana 7 vimos el sigueinte ejemplo

In [14]:
from scipy.sparse import csr_matrix
import numpy as np

# Crear una matriz dispersa CSR
data = [4, 5, 7]
row_indices = [0, 1, 1]
col_indices = [0, 1, 2]

csr = csr_matrix((data, (row_indices, col_indices)), shape=(3, 3))

# Multiplicar la matriz dispersa por un vector
vector = np.array([1, 0, 1])
result = csr.dot(vector)
print(result)


[4 7 0]


Ahora, para lo solicitado como tarea

In [23]:
from scipy.sparse import csr_matrix

# Definir los datos no nulos de la matriz
valores = [3, 4, 5, 5, 8]
filas = [0, 1, 5, 6, 6]
columnas = [0, 0, 5, 0, 2]

# Crear la matriz en formato CSR
matriz_csr = csr_matrix((valores, (filas, columnas)), shape=(8, 8))
print("Matriz formato CSR")
print(matriz_csr)

# Mostrar los vectores de la matriz CSR
print("\nValores:", matriz_csr.data)
print("Punteros de las filas:", matriz_csr.indptr)
print("Índices de columna:", matriz_csr.indices)

# Matriz CSR en su forma completa
matriz_densa = matriz_csr.toarray()
print("\nMatriz completa:")
print(matriz_densa)



Matriz formato CSR
  (0, 0)	3
  (1, 0)	4
  (5, 5)	5
  (6, 0)	5
  (6, 2)	8

Valores: [3 4 5 5 8]
Punteros de las filas: [0 1 2 2 2 2 3 5 5]
Índices de columna: [0 0 5 0 2]

Matriz completa:
[[3 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 5 0 0]
 [5 0 8 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
